### PR TITLE
Support installation of clangd binaries if not found.

### PR DESCRIPTION
**Pull request by sam-mccall**
Also has auto-update checks, but turned off by default for now.

See:
- Library with main logic: https://github.com/clangd/node-clangd/commit/3ce82ac0b4afe9c98c7a0f552d4d4b5d7637a83c
- PR for vscode-clangd: https://github.com/clangd/vscode-clangd/pull/5

### CODE REVIEW

**Comment by fannheyward** [comment]
I make two small commits:

1. `@clangd/install` as devDependencies, this will bundle all dependencies by webpack, to a single lib/index.js file.
2. run `editor.action.restart` after download, no more `:CocRestart` needed.

**Comment by oblitum** [comment]
Just missed an update to README which states this is not supported.

**Comment by oblitum** [comment]
Will this grab clangd from prereleases as well or just releases?

Another question is if I enable this will it override my system installation correctly (since clangd comes bundled to clang)?

**Comment by fannheyward** [comment]
@oblitum just latest release https://github.com/clangd/node-clangd/commit/3ce82ac0b4afe9c98c7a0f552d4d4b5d7637a83c#diff-f41e9d04a45c83f3b6f6e630f10117feR146

**Comment by oblitum** [comment]
@fannheyward ah, ok, thanks!

**Comment by fannheyward** [comment]
@sam-mccall @hokein this will update `clangd.path` in `coc-settings.json`?

**Comment by sam-mccall** [comment]
@fannheyward Thanks! LGTM

> this will update clangd.path in coc-settings.json?

Correct, it'll install a portable clangd (just unzip the release) under `~/.config/coc/extensions/coc-clangd-data/install/`, and then update coc's `clangd.path` setting to point to it. The rest of the system is not affected.

**Pull request merged**
